const RandExp = require('randexp')
const randexp = new RandExp(/[a-z]{6}/)
console.log(randexp.gen())
console.log(randexp.gen())
console.log(randexp.gen())
const phone = new RandExp(/1110000[\d]{4}/)
console.log(phone.gen())
console.log(phone.gen())
console.log(phone.gen())
